korpus_main_page_homepage:
    pattern:  /
    defaults: { _controller: KorpusMainPageBundle:Page:index }
    
korpus_main_page_next_concerts:
    pattern:  /concerts/next/{max}
    defaults: { _controller: KorpusMainPageBundle:Sidebar:nextConcerts }

#old news route
korpus_main_page_news_old:
    pattern:  /news/post/{number}
    defaults: { _controller: KorpusMainPageBundle:Page:news }

#news
korpus_main_page_news:
    pattern:  /news
    defaults: { _controller: KorpusMainPageBundle:Page:news }
    
korpus_main_page_news_list:
    pattern:  /news/list
    defaults: { _controller: KorpusMainPageBundle:Page:newsList }
    
korpus_main_page_news_post:
    pattern:  /news/{day}/{month}/{year}/{slug}
    defaults: { _controller: KorpusMainPageBundle:Page:newsPost }
        
#impressum
korpus_main_page_impressum:
    pattern:  /impressum
    defaults: { _controller: KorpusMainPageBundle:Page:impressum }
    
#datenschutz
korpus_main_page_datenschutz:
    pattern:  /datenschutz
    defaults: { _controller: KorpusMainPageBundle:Page:datenschutz }
    
#band
korpus_main_page_band:
    pattern:  /band
    defaults: { _controller: KorpusMainPageBundle:Page:band }
    
korpus_main_page_bio:
    pattern:  /band/bio
    defaults: { _controller: KorpusMainPageBundle:Page:bio }
    
korpus_main_page_member:
    pattern:  /band/member/{name}
    defaults: { _controller: KorpusMainPageBundle:Page:member, name: null }
    
#live
korpus_main_page_live:
    pattern:  /live
    defaults: { _controller: KorpusMainPageBundle:Page:live }
    
korpus_main_page_live_concert:
    pattern:  /live/concert/{slug}
    defaults: { _controller: KorpusMainPageBundle:Page:concert }
    
korpus_main_page_live_events:
    pattern:  /live/events
    defaults: { _controller: KorpusMainPageBundle:Page:events }
    
korpus_main_page_live_event:
    pattern:  /live/events/{slug}
    defaults: { _controller: KorpusMainPageBundle:Page:event }
    
#media
korpus_main_page_media:
    pattern:  /media
    defaults: { _controller: KorpusMainPageBundle:Page:media }
    
korpus_main_page_audio:
    pattern:  /media/audio
    defaults: { _controller: KorpusMainPageBundle:Page:audio }
    
korpus_main_page_video:
    pattern:  /media/video
    defaults: { _controller: KorpusMainPageBundle:Page:video }
    
korpus_main_page_lyrics:
    pattern:  /media/lyrics
    defaults: { _controller: KorpusMainPageBundle:Page:lyrics }
        
korpus_main_page_photos:
    pattern:  /media/photos
    defaults: { _controller: KorpusMainPageBundle:Page:photos }
    
#kontakt
korpus_main_page_kontakt:
    pattern:  /contact
    defaults: { _controller: KorpusMainPageBundle:Page:contact }
    
korpus_main_page_kontakt_booking:
    pattern:  /contact/booking
    defaults: { _controller: KorpusMainPageBundle:Page:booking }
    
korpus_main_page_kontakt_links:
    pattern:  /contact/links
    defaults: { _controller: KorpusMainPageBundle:Page:links }
    
#merch
korpus_main_page_merch:
    pattern:  /merch
    defaults: { _controller: KorpusMainPageBundle:Page:merch }
    
korpus_main_page_merch_article:
    pattern:  /merch/{slug}
    defaults: { _controller: KorpusMainPageBundle:Page:merchArticle }