Korpus\DataBundle\Entity\File:
    type: entity
    table: null
    repositoryClass: Korpus\DataBundle\Entity\FileRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        hash:
            type: string
            length: 255
        path:
            type: string
            length: 255
    lifecycleCallbacks: {  }
