korpus_admin_panel:
    resource: "@KorpusAdminPanelBundle/Resources/config/routing.yml"
    prefix:   /admin

korpus_events:
    resource: "@KorpusEventsBundle/Resources/config/routing.yml"
    prefix:   /events

korpus_console:
    resource: "@KorpusConsoleBundle/Resources/config/routing.yml"
    prefix:   /console

korpus_backup:
    resource: "@KorpusBackupBundle/Resources/config/routing.yml"
    prefix:   /console

korpus_file_server:
    resource: "@KorpusFileServerBundle/Resources/config/routing.yml"
    prefix:   /filesystem
    options:
        expose: true

#korpus_data:
    #resource: "@KorpusDataBundle/Resources/config/routing.yml"
    #prefix:   /

korpus_main_page:
    resource: "@KorpusMainPageBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_user_bundle:
    resource: "@KorpusUserBundle/Resources/config/routing.yml"