korpus_data:
    resource: "@KorpusDataBundle/Resources/config/routing.yml"
    prefix:   /

korpus_console:
    resource: "@KorpusConsoleBundle/Resources/config/routing.yml"
    prefix:   /console

korpus_main_page:
    resource: "@KorpusMainPageBundle/Resources/config/routing.yml"
    prefix:   /

