korpus_file_server:
    resource: "@KorpusFileServerBundle/Resources/config/routing.yml"
    prefix:   /filesystem

#korpus_data:
    #resource: "@KorpusDataBundle/Resources/config/routing.yml"
    #prefix:   /

korpus_main_page:
    resource: "@KorpusMainPageBundle/Resources/config/routing.yml"
    prefix:   /
    
korpus_console:
    resource: "@KorpusConsoleBundle/Resources/config/routing.yml"
    prefix:   /console
