parameters:
#    korpus_file_server.example.class: Korpus\FileServerBundle\Example

services:
#    korpus_file_server.example:
#        class: %korpus_file_server.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
