<?php

namespace Korpus\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConcertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcertRepository extends EntityRepository
{

    public function findNextConcerts()
    {
        //entity manager
        $em = $this->getEntityManager();

        //today, date part
        $today = new \DateTime('now');
        $today->setTime(0, 0, 0);

        $dql = 'select c from KorpusDataBundle:Concert c where c.concertDate >= ?1 order by c.concertDate asc';

        $query = $em->createQuery($dql);
        $query->setParameter(1, $today);

        $concerts = $query->getResult();

        if (!$concerts)
            return null;

        return $concerts;
    }

}
