<?php

namespace Korpus\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileTypeRepository extends EntityRepository
{
    public function findAllActiveTypes() {
        //entity manager
        $em = $this->getEntityManager();        
        $dql = 'select ft from KorpusDataBundle:FileType ft where ft.isActive = true';        
        $query = $em->createQuery($dql);
        return $query->getResult();
    }
}
