<?php

namespace Korpus\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordRepository extends EntityRepository
{

    public function findAllWithTracks()
    {
        //entity manager
        $em = $this->getManager();

        $records = $this->findAll();
        $out = array();

        foreach ($records as $record) {
            $out[] = array(
                $record,
                $record->getTracks()
            );
        }
                
        return $out;
    }

}
