korpus_console_homepage:
    pattern:  /
    defaults: { _controller: KorpusConsoleBundle:Page:index }

korpus_console_dashboard:
    pattern:  /dashboard
    defaults: { _controller: KorpusConsoleBundle:Page:dashboard }
    
korpus_console_add_user:
    pattern:  /user/create
    defaults: { _controller: KorpusConsoleBundle:Page:addUser }

#NewsPost
korpus_console_news_posts:
    resource: "@KorpusConsoleBundle/Resources/config/NewsPost/routing.yml"
    prefix:   /news

#cms news
korpus_console_cms_news:
    pattern:  /cms/news
    defaults: { _controller: KorpusConsoleBundle:CMS:news }
    
korpus_console_cms_news_create:
    pattern:  /cms/news/create
    defaults: { _controller: KorpusConsoleBundle:CMS:createNews }
    
korpus_console_cms_news_update:
    pattern:  /cms/news/{slug}/edit
    defaults: { _controller: KorpusConsoleBundle:CMS:updateNews }
    
korpus_console_cms_news_delete:
    pattern:  /cms/news/{slug}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteNews }

#Concert
korpus_console_concerts:
    resource: "@KorpusConsoleBundle/Resources/config/Concert/routing.yml"
    prefix:   /concerts

#cms concert
korpus_console_cms_concert:
    pattern:  /cms/concert
    defaults: { _controller: KorpusConsoleBundle:CMS:concert }
    
korpus_console_cms_concert_create:
    pattern:  /cms/concert/create
    defaults: { _controller: KorpusConsoleBundle:CMS:createConcert }
    
korpus_console_cms_concert_update:
    pattern:  /cms/concert/{slug}/edit
    defaults: { _controller: KorpusConsoleBundle:CMS:updateConcert }
    
korpus_console_cms_concert_delete:
    pattern:  /cms/concert/{slug}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteConcert }
    
#cms member
korpus_console_cms_member:
    pattern:  /cms/member
    defaults: { _controller: KorpusConsoleBundle:CMS:member }
    
korpus_console_cms_member_create:
    pattern:  /cms/member/create
    defaults: { _controller: KorpusConsoleBundle:CMS:createMember }
    
korpus_console_cms_member_update:
    pattern:  /cms/member/{nickname}/edit
    defaults: { _controller: KorpusConsoleBundle:CMS:updateMember }
    
korpus_console_cms_member_delete:
    pattern:  /cms/member/{nickname}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteMember }

#file upload
korpus_console_file_upload:
    pattern:  /upload/file
    defaults: { _controller: KorpusConsoleBundle:Upload:file }
    methods: [POST]

#cms files
korpus_console_cms_files:
    pattern:  /cms/files
    defaults: { _controller: KorpusConsoleBundle:CMS:files }
    
#images
korpus_console_cms_files_images:
    pattern:  /cms/files/images
    defaults: { _controller: KorpusConsoleBundle:CMS:images }
    
korpus_console_cms_files_images_delete:
    pattern:  /cms/files/images/{slug}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteImage }
    
#file type
korpus_console_cms_files_filetype_create:
    pattern:  /cms/files/filetype/create
    defaults: { _controller: KorpusConsoleBundle:CMS:createFilesFileType }
    
korpus_console_cms_files_filetype_update:
    pattern:  /cms/files/filetype/{title}/edit
    defaults: { _controller: KorpusConsoleBundle:CMS:updateFilesFileType }
    
korpus_console_cms_files_filetype_delete:
    pattern:  /cms/files/filetype/{title}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteFilesFileType }
    
#file type group
korpus_console_cms_files_filetypegroup_create:
    pattern:  /cms/files/filetypegroup/create
    defaults: { _controller: KorpusConsoleBundle:CMS:createFilesFileTypeGroup }
    
korpus_console_cms_files_filetypegroup_update:
    pattern:  /cms/files/filetypegroup/{id}/edit
    defaults: { _controller: KorpusConsoleBundle:CMS:updateFilesFileTypeGroup }
    
korpus_console_cms_files_filetypegroup_delete:
    pattern:  /cms/files/filetypegroup/{id}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteFilesFileTypeGroup }

#cms media
korpus_console_cms_media:
    pattern:  /cms/media
    defaults: { _controller: KorpusConsoleBundle:CMS:media }
    
#records    
korpus_console_cms_media_record_create:
    pattern:  /cms/media/record/create
    defaults: { _controller: KorpusConsoleBundle:CMS:createMediaRecord }
    
korpus_console_cms_media_record_update:
    pattern:  /cms/media/record/{title}/edit
    defaults: { _controller: KorpusConsoleBundle:CMS:updateMediaRecord }
    
korpus_console_cms_media_record_delete:
    pattern:  /cms/media/record/{title}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteMediaRecord }
    
#merch
korpus_console_shop_articles:
    pattern:  /shop/articles
    defaults: { _controller: KorpusConsoleBundle:Shop:articles }
    
korpus_console_shop_articles_create:
    pattern:  /shop/articles/create
    defaults: { _controller: KorpusConsoleBundle:Shop:createArticle }
    
korpus_console_shop_articles_update:
    pattern:  /shop/articles/{slug}/update
    defaults: { _controller: KorpusConsoleBundle:Shop:updateArticle }
    
korpus_console_shop_articles_delete:
    pattern:  /shop/articles/{slug}/delete
    defaults: { _controller: KorpusConsoleBundle:Shop:deleteArticle }
    
#events
korpus_console_events:
    pattern:  /events
    defaults: { _controller: KorpusConsoleBundle:Events:index }
    
korpus_console_events_toggle_viewable:
    pattern:  /events/{slug}/toggleViewable
    defaults: { _controller: KorpusConsoleBundle:Events:toggleViewable }
    methods: [POST]
    options:
        expose: true
    
korpus_console_events_toggle_reservable:
    pattern:  /events/{slug}/toggleReservable
    defaults: { _controller: KorpusConsoleBundle:Events:toggleReservable }
    methods: [POST]
    options:
        expose: true

korpus_console_events_reservations:
    pattern:  /events/{id}/reservations
    defaults: { _controller: KorpusConsoleBundle:Events:reservations }

korpus_console_events_reservations_print:
    pattern:  /events/{id}/reservations/print
    defaults: { _controller: KorpusConsoleBundle:Events:printReport }
