korpus_console_homepage:
    pattern:  /
    defaults: { _controller: KorpusConsoleBundle:Page:index }

korpus_console_dashboard:
    pattern:  /dashboard
    defaults: { _controller: KorpusConsoleBundle:Page:dashboard }

#cms news
korpus_console_cms_news:
    pattern:  /cms/news
    defaults: { _controller: KorpusConsoleBundle:CMS:news }
    
korpus_console_cms_news_create:
    pattern:  /cms/news/create
    defaults: { _controller: KorpusConsoleBundle:CMS:createNews }
    
korpus_console_cms_news_update:
    pattern:  /cms/news/{slug}/edit
    defaults: { _controller: KorpusConsoleBundle:CMS:updateNews }
    
korpus_console_cms_news_delete:
    pattern:  /cms/news/{slug}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteNews }
    
#cms concert
korpus_console_cms_concert:
    pattern:  /cms/concert
    defaults: { _controller: KorpusConsoleBundle:CMS:concert }
    
korpus_console_cms_concert_create:
    pattern:  /cms/concert/create
    defaults: { _controller: KorpusConsoleBundle:CMS:createConcert }
    
korpus_console_cms_concert_update:
    pattern:  /cms/concert/{slug}/edit
    defaults: { _controller: KorpusConsoleBundle:CMS:updateConcert }
    
korpus_console_cms_concert_delete:
    pattern:  /cms/concert/{slug}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteConcert }
    
#cms member
korpus_console_cms_member:
    pattern:  /cms/member
    defaults: { _controller: KorpusConsoleBundle:CMS:member }
    
korpus_console_cms_member_create:
    pattern:  /cms/member/create
    defaults: { _controller: KorpusConsoleBundle:CMS:createMember }
    
korpus_console_cms_member_update:
    pattern:  /cms/member/{nickname}/edit
    defaults: { _controller: KorpusConsoleBundle:CMS:updateMember }
    
korpus_console_cms_member_delete:
    pattern:  /cms/member/{nickname}/delete
    defaults: { _controller: KorpusConsoleBundle:CMS:deleteMember }
    