parameters:
#    korpus_console.example.class: Korpus\ConsoleBundle\Example

services:
#    korpus_console.example:
#        class: %korpus_console.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
