Korpus\DataBundle\Entity\NewsPost:
    properties:
        title:
            - NotBlank: ~
        text:
            - NotBlank: ~
        publishDate:
            - NotBlank: ~
            - Type: \DateTime
            
Korpus\DataBundle\Entity\Concert:
    properties:
        eventName:
            - NotBlank: ~
        venue:
            - NotBlank: ~
        city:
            - NotBlank: ~
        state:
            - NotBlank: ~
        concertDate:
            - NotBlank: ~
            - Type: \DateTime

Korpus\DataBundle\Entity\Event:
    properties:
        title:
            - NotBlank: ~
        venue:
            - NotBlank: ~
        city:
            - NotBlank: ~
        eventDate:
            - NotBlank: ~
            - Type: \DateTime