Korpus\DataBundle\Entity\NewsPost:
    properties:
        title:
            - NotBlank: ~
        text:
            - NotBlank: ~
        publishDate:
            - NotBlank: ~
            - Type: \DateTime
            
Korpus\DataBundle\Entity\Concert:
    properties:
        event:
            - NotBlank: ~
        venue:
            - NotBlank: ~
        city:
            - NotBlank: ~
        concertDate:
            - NotBlank: ~
            - Type: \DateTime