<?php

namespace Korpus\LoggingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLogRepository extends EntityRepository
{
    
}
